name: balls

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    balls:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: Tailscale
              uses: tailscale/github-action@v2
              with:
                  authkey: "tskey-auth-k4nWstLfac11CNTRL-5tYL5YR8T3F8q6vezwbM3FyxfhN98CKae"
                  statedir: /tmp/tailscale-state/

            - name: node
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: server
              run: |
                  node index.js
