name: balls

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    balls:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v3

            - name: node
              uses: actions/setup-node@v3
              with:
                  node-version: "16"

            - name: server
              run: |
                  nohup node server.js &
                  echo "running"
